<!-- 这是导航栏 -->
document.writeln("<nav class=\'navbar navbar-default\'>");
document.writeln("		  <div class=\'container-fluid\'>");
document.writeln("		    <!-- Brand and toggle get grouped for better mobile display -->");
document.writeln("		    <div class=\'navbar-header\'>");
document.writeln("		      <button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#bs-example-navbar-collapse-1\' aria-expanded=\'false\'>");
document.writeln("		        <span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("		        <span class=\'icon-bar\'></span>");
document.writeln("		        <span class=\'icon-bar\'></span>");
document.writeln("		        <span class=\'icon-bar\'></span>");
document.writeln("		      </button>");
document.writeln("		      <a class=\'navbar-brand\' href=\'./index.html\' style=\'color:#000000\'>IEEE MLSP 2023 Data Challenge - Volunteer Retention and Future Collaboration Prediction</a>");
document.writeln("		    </div>");
document.writeln("");
document.writeln("		    <!-- Collect the nav links, forms, and other content for toggling -->");
// document.writeln("		    <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
// document.writeln("		      <ul class=\'nav navbar-nav\'>");
// document.writeln("		        <li><a href=\'./competition-message.html\'>竞赛讯息 <span class=\'sr-only\'>(current)</span></a></li>");
// document.writeln("		        <li><a href=\'./question.html\'>常见问题</a></li>");
// document.writeln("		        <li class=\'dropdown\'>");
// document.writeln("		          <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-haspopup=\'true\' aria-expanded=\'false\'>学习资料<span class=\'caret\'></span></a>");
// document.writeln("		          <ul class=\'dropdown-menu\'>");
// document.writeln("		            <li><a href=\'#\'>土木（待合作）</a></li>");
// document.writeln("		            <li><a href=\'#\'>机械（待合作）</a></li>");
// document.writeln("		            <li><a href=\'#\'>电信（待合作）</a></li>");
// document.writeln("		            <li><a href=\'#\'>计算机</a></li>");
// document.writeln("		            <li role=\'separator\' class=\'divider\'></li>");
// document.writeln("		            <li><a href=\'./study-resource.html\'>其他</a></li>");
// document.writeln("		          </ul>");
// document.writeln("		        </li>");
// document.writeln("		      </ul>");
// document.writeln("		    </div><!-- /.navbar-collapse -->");
document.writeln("		  </div><!-- /.container-fluid -->");
document.writeln("		</nav>");
